name: cupertino_youtube_player
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 10.0.1
repository: https://github.com/stelynx/cupertino_youtube_player
homepage: https://github.com/stelynx/cupertino_youtube_player/tree/master/packages/cupertino_youtube_player
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview:
    path: ../flutter_inappwebview

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1

flutter:
  assets:
    - assets/speedometer.webp
